### ISSUE TITLE
"Display color + short results outcome" hard to read / doesn't look great with Dorako UI CRB chat theme

### ISSUE THREAD

**Issue by weepingminotaur** [reyzor1991/pf2e-wiki#13]
Screenshot attached. I would recommend abandoning the colour bar background across the whole line and just making the results portion of the line coloured.

I would also recommend standardizing the colours (crit success, success, fail, crit fail) to match Dorako, a mod that is used by many Pf2e Foundry users. It is confusing and unnecessarily counter-intuitive to have to think about what a new set of colours means just in the context of ASE. Particularly when those same Dorako colours show up in the saving throw results. I know you can use Custom CSS to change colours, but that shouldn't be necessary. ASE isn't a UI mod. Why not match the UI mod?

<img width="321" alt="Screenshot 2023-12-01 at 9 28 18 PM" src="https://github.com/reyzor1991/pf2e-wiki/assets/90105219/6f7b50dd-cd64-4ce8-8556-ebd06f714ac1">

**Comment by reyzor1991** [comment]
Also you could use custom css for it
