### ISSUE TITLE
[FEATURE] Remove critical success from damage list

### ISSUE THREAD

**Issue by uniwars** [reyzor1991/pf2e-wiki#20]
Hi,
![image](https://github.com/reyzor1991/pf2e-wiki/assets/65986545/965b681c-19d9-410d-83e8-85147e5ea0f4)

**Describe the solution you'd like**
Remove or add a setting to remove critical success from the damaged actors list, refreshing it if the result is rerolled and the actor should now appears.

**Describe alternatives you've considered**
If it's impossible to remove crit success it would be nice to at least have the option to remove the glass overlay to make the line less flashy with some UI theme.

**Comment by reyzor1991** [comment]
Next release
