### ISSUE TITLE
Double slice macro issues

### ISSUE THREAD

**Issue by uniwars** [reyzor1991/pf2e-wiki#21]
**Describe the bug**
Hi, if the damage pop-ups are not unchecked then when using the macro they will pop and lead to rolling 2x damages and then the combined damage if both attacks hit. 

Also the macro doesn't ask which weapon to use as primary/secondary which may be useful to switch based of the enemy.

Lastly the "Double slice second attack" toggle stay ON after the macro has run, so if not toggling it off by hand we get the malus for our normal attacks.

**Expected behavior**
If user has damage pop-ups not unchecked the macro should count as if it has "shift+click" the damage to not show the pop-up and only roll the combined damage.

Macro in addition to asking for map should ask for primary weapon.

Macro should toggle off "Double slice second attack" at its end.

**Comment by reyzor1991** [comment]
switch weapon not need because PC should have only 2 equipped weapons for this Action. And weapon with agile is always second to increase accuracy

**Comment by uniwars** [comment]
my player has two weapon without agile and would like to choose which one to use as primary without the -2 malus depending on the rune of his weapons
