### ISSUE TITLE
[FEATURE] Forceful trait auto-apply setting

### ISSUE THREAD

**Issue by uniwars** [reyzor1991/pf2e-wiki#23]
**Is your feature request related to a problem? Please describe.**
Hi, when using a forceful weapon the GM could apply damage before the player had the time to apply forceful by clicking on the button. In the vast majority of time Forceful bonus damage are linked to the actual MAP (not 100% RAW true, but I believe it's the vast majority of cases).

**Describe the solution you'd like**
Could the module add a setting to auto-apply forceful to damage based on MAP of the attack ? (-5/4 forceful x1 and -10 forceful x2).
That way it would save time and avoid GM applying damage too soon, at the cost of the automation being wrong in few cases (like using power attack and then making an attack at -10, which being the second attack with the weapon should be forceful x1 and not forceful x2).

**Describe alternatives you've considered**
The best way would be to have a way to count how many times a weapon has been used in the actor turn and link forcefull automation to that counter instead of MAP, so if using pwoer attack with a weapon it would log one use of this weapon and if attacking again with it it would be the second use so forceful x1.

This logging could be used for other automation like sweep.

**Comment by reyzor1991** [comment]
This part hard to automate, because MAP not an indicator for attack with same weapon during turn, action like Escape change MAP also some feats and etc

**Comment by uniwars** [comment]
could an hidden effect be added when attacking with a forceful weapon ? when making an attack with it it would add "forceful 1" and if forceful 1 is active then it would auto-apply forceful damage on the next attack and increment to forceful 2 and remove the effect at the end of turn

**Comment by reyzor1991** [comment]
I always could try to do it, but this logic wouldn't work with Workbench auto roll damage. Because when you attack I need to save forceful 1/2 in parallel Worckbench would roll damage

**Comment by uniwars** [comment]
is that impossible to apply forceful after damage has been rolled by workbench ? Like auto-clicking on the "apply forceful" button if the forceful 1/2 effect is detected ?

If that's way too complicated to make I guess your time would be better spent on something else yeah

**Comment by reyzor1991** [comment]
Support by pf2e now
