### ISSUE TITLE
Bug : Sustain reminder issues

### ISSUE THREAD

**Issue by uniwars** [reyzor1991/pf2e-wiki#26]
**Describe the bug**
Hi, when using Courageous Anthem brom bard I noticed 3 things :
The "Spells ha sbeen sustained" is sent multiple time.
The spell effect is removed before I had tghe chance to sustain the spell and after sustaining it the spell effect did not came back.
When the spell card is still in the chat it will focus on it when sustaining, scrolling up in the chat instead of staying at the end of the chat log.

**To Reproduce**
Go in encoutner with 2 allied tokens
Cast the courageous anthem and skip turn until it's the catser turn again

**Screenshots**
![image](https://github.com/reyzor1991/pf2e-wiki/assets/65986545/ad71665b-36ee-401c-be50-409da5b3075b)

**Comment by git-kor-av** [comment]
If you use workbench to generate the Bard Auras, then this is a problem with Workbench, not ASE's Sustain reminder.  In general these spells are not sustained, they are cast each round unless performing a Lingering Composition.

See this bug that was opened and resolved yesterday by xdy:  https://github.com/xdy/xdy-pf2e-workbench/issues/1197

**Comment by uniwars** [comment]
I did update workbench and my courageous anthem was freshly imported from compendium

I only casted the spell, not using any macro

When the spell is casted it adds aura for it so I guess it uses the workbench thing

**Comment by git-kor-av** [comment]
Interesting, I was unaware that these were also part of the ASE - Effects compendium.  It does seem that there is a problem with these effects as well:
![image](https://github.com/reyzor1991/pf2e-wiki/assets/32276185/acb61625-fc06-48d5-852d-bda444dac86e)

It seems to me that the Sustained Flag needs to be removed from each of the open effects.  It would also be good if they were renamed to the Remaster.

**Comment by reyzor1991** [comment]
Duplication would be fixed next release, sustain spells - fixed
