### ISSUE TITLE
[FEATURE] Larger buttons for multiple target saving throws

### ISSUE THREAD

**Issue by Qenthel94** [reyzor1991/pf2e-wiki#27]
**Is your feature request related to a problem? Please describe.**
Whenever a spell, or action with saving throws is posted in public, the saving throw buttons are these tiny little dice icons under the action/spell card. It feels uncomfortable having to click such small icons and players often miss that need to roll something. 

**Describe the solution you'd like**
I would love if we could use choose to use the saving throw buttons that we get spell/action is cast privately to be available everywhere instead of the small dice icons. They are much easier to see and feel better to click. Although right now these buttons seem to have the coloring bugged and only critical  success has a colored tint. If we get a nice coloring for each degree of success and and big buttons replacing the small dice icons, it would make the experience so much better for us. Maybe have it as a toggle or another option in the dropdown for the button configuration?

**Additional context**
![Screenshot 2024-01-13 023336](https://github.com/reyzor1991/pf2e-wiki/assets/87117602/b5c8455f-5c17-4c3a-b785-931caaa0f228)

**Comment by roi007leaf** [comment]
The small buttons aren't for players, you have 2 options: use monks token bar or ASE own implementation. When using ASE own implementation the players will see the big save button under the public spell message.

Best regards,
Roi Horowitz

**Comment by Qenthel94** [comment]
> The small buttons aren't for players, you have 2 options: use monks token bar or ASE own implementation. When using ASE own implementation the players will see the big save button under the public spell message. Best regards, Roi Horowitz
> […](#)
> On Jan 13, 2024, 03:41 +0200, Qenthel94 ***@***.***>, wrote: Is your feature request related to a problem? Please describe. Whenever a spell, or action with saving throws is posted in public, the saving throw buttons are these tiny little dice icons under the action/spell card. It feels uncomfortable having to click such small icons and players often miss that need to roll something. Describe the solution you'd like I would love if we could use choose to use the saving throw buttons that we get spell/action is cast privately to be available everywhere instead of the small dice icons. They are much easier to see and feel better to click. Although right now these buttons seem to have the coloring bugged and only critical success has a colored tint. If we get a nice coloring for each degree of success and and big buttons replacing the small dice icons, it would make the experience so much better for us. Maybe have it as a toggle or another option in the dropdown for the button configuration? Additional context Screenshot.2024-01-13.023336.png (view on web) — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you are subscribed to this thread.Message ID: ***@***.***>

Could we get

**Comment by roi007leaf** [comment]
@reyzor1991 is that possible?

**Comment by reyzor1991** [comment]
In general yes, but need time
