### ISSUE TITLE
[FEATURE] Include ability traits in the message for privately posted abilities with saving throws

### ISSUE THREAD

**Issue by Qenthel94** [reyzor1991/pf2e-wiki#28]
**Is your feature request related to a problem? Please describe.**
Whenever a monster uses an ability I want the players to know all the traits it has, so that I don't get asked every single time "Is this a manipulate action?"  kind of questions, but I don't want players to know what the ability does exactly.
**Describe the solution you'd like**
It would be great if the "They just used an action" message that gets posted when posting abilities privately, would describe the traits that this ability has. Similarly to what workbench does with private spells.

**Additional context**
![Screenshot 2024-01-13 150254](https://github.com/reyzor1991/pf2e-wiki/assets/87117602/c24def76-dc74-475f-a67e-e6bca2609ba8)

**Comment by uniwars** [comment]
workbench has a feature like this for privately casted spells

with reaction checker module players already get a notification if the monster action triggered something, but yeah I still get the question popping because players have doubts if everything is atuomated
