### ISSUE TITLE
Helpful Halfling Ancestry Feat and Aid [Action Support Engine]

### ISSUE THREAD

**Issue by git-kor-av** [reyzor1991/pf2e-wiki#3]
Currently the Aid macro doesn't consider the Helpful Halfling Ancestry Feat (same feat exists in the Remaster) as described here:
https://2e.aonprd.com/Feats.aspx?ID=1021

It would be good if the Aid macro could check for this feature and provide the appropriate value for the target of the Aid.

NOTE:  I added another issue for supporting One_for_All, the Helpful Halfling feature is something to consider for that feature as well.

**Comment by reyzor1991** [comment]
Added in 0.0.73
