### ISSUE TITLE
[FEATURE]  auto-collapse the top row of damage 

### ISSUE THREAD

**Issue by reyzor1991** [reyzor1991/pf2e-wiki#32]
auto-collapse the top row of damage buttons or hide the bottom row for single-target attacks and spells?

![image](https://github.com/reyzor1991/pf2e-wiki/assets/6688366/7b088d99-a1fe-4592-98b9-a4120c79f5ed)

**Comment by uniwars** [comment]
you already implemented a setting for this :

![image](https://github.com/reyzor1991/pf2e-wiki/assets/65986545/e0810c42-07e1-4212-a2c6-9ec765004375)
