### ISSUE TITLE
[FEATURE] Roll Flat Check for spells when under Deafened condition

### ISSUE THREAD

**Issue by Qenthel94** [reyzor1991/pf2e-wiki#35]
Would it be possible to add a flat check roll to a spell that is cast under the Deafened condition and does not have the subtle trait?
Its not explicitly stated under the condition and is instead spread over multiple rules, so maybe have it controlled by a toggle if some ppl don't want to rule it that way?

These are the rules from player core:
- Deafened Condition: If you perform an action that has the auditory trait, you must succeed at a DC 5 flat check or the action is lost
- All speech has the auditory trait
- Casting a spell requires the caster to make gestures and utter incantations, so being unable to speak prevents spellcasting for most casters
- Subtle trait: A spell with the subtle trait can be cast without incantations

**Comment by reyzor1991** [comment]
Next release
