### ISSUE TITLE
Inspire Heroics / Fortissimo Composition Macro does not reduce Focus Points

### ISSUE THREAD

**Issue by git-kor-av** [reyzor1991/pf2e-wiki#4]
Using the Inspire Heroics / Fortissimo Composition Macro, it works great, however it does not use up a focus point when using it.  Attached is a screenshot showing the roll happening, but there are still 3 focus points.

![Screenshot 2023-11-24 001135](https://github.com/reyzor1991/pf2e-wiki/assets/32276185/9c8e1696-92b4-493a-b152-ee7cf8ebde01)

**Comment by reyzor1991** [comment]
Fixed
