### ISSUE TITLE
[FEATURE] Toggle to enable/disable automated application of the afflictions effects

### ISSUE THREAD

**Issue by Qenthel94** [reyzor1991/pf2e-wiki#41]
**Is your feature request related to a problem? Please describe.**
Right now there seem to be an automation in place that auto-applies the affliction based on the result of saving throws.  This causes two challenges for me:
1. It applies the effects/conditions before the player decides whether to hero point the saving throw.
2. Sometimes the effects of the affliction don't match the ones that should be  applied. For example variant or elite/weak versions of creatures often have different damage DCs on afflictions than the ones in the compendium. Another example are scaling afflictions from spells, like curse of death.

**Describe the solution you'd like**
I wouldn't mind being able to manually handle the application of afflictions, so that I can wait for players to use their hero points/other fortune abilities first and to make sure that the correct "variant" version of the affliction is applied in case of variant creatures or scaling spells. So maybe a toggle in the settings that dictates whether the application is automatic?

**Comment by reyzor1991** [comment]
<img width="1089" alt="Screenshot 2024-02-07 at 14 39 00" src="https://github.com/reyzor1991/pf2e-wiki/assets/6688366/27b92749-d83c-45f3-b031-1d9d3eb6b2a2">
