### ISSUE TITLE
[FEATURE] Add support for Scoundrel Feint mechanics

### ISSUE THREAD

**Issue by git-kor-av** [reyzor1991/pf2e-wiki#47]
As part of PF2 Automations would it be possible to add support for the special conditions associated with Feint and the Scoundrel racket, specifically as described here:
"When you successfully [Feint](https://2e.aonprd.com/Actions.aspx?ID=48), the target is [off-guard](https://2e.aonprd.com/Conditions.aspx?ID=16) against your melee attacks until the end of your next turn. On a critical success, the target is off-guard against all melee attacks until the end of your next turn, not just yours."

For reference, this is specified here:
https://2e.aonprd.com/Rackets.aspx?ID=8&Redirected=1

**Comment by reyzor1991** [comment]
Next release
