### ISSUE TITLE
[NEW MODULE] - PF2e encounter and game stats

### ISSUE THREAD

**Issue by Zal4DW** [reyzor1991/pf2e-wiki#55]
**Is your feature request related to a problem? Please describe.**
There was an excellent module, encounter statistics which had basic PF2e integration, but its v11 and not that great...

**Describe the solution you'd like**
A brand new encounter and game tracking tool that records events, dicerolls, spells cast etc and can also export the data into a format for other use out of game. (for example as input into an AI to generate a stats based podcast of the game, which is what I do!)

**Describe alternatives you've considered**
encounter-stats , really only works for v11 and dnd5e, the code is also super heavy in tests and typescript, so beyond my meagre hacking skills!

**Additional context**

**Comment by reyzor1991** [comment]
For so big module I think need to create roadmap to understood steps

**Comment by Zal4DW** [comment]
happy to provide whatever input you need to help

**Comment by reyzor1991** [comment]
For init version fields are:

**Encounter**
- createdAt
- endedAt
- sceneName
- totalRounds
- combatants

**Combatant**
- id
- initiative
- rounds
- ac
- start HP
- end HP

**Rounds**
- number of round
- kills
- damage
- heal
- actions

**Actions**
- item
- attack roll
- damage from roll

**Comment by reyzor1991** [comment]
What information do you this is must have for init version?

**Comment by reyzor1991** [comment]
<img width="889" alt="Screenshot 2024-07-22 at 12 53 56" src="https://github.com/user-attachments/assets/925e552f-d72e-4d55-a056-ba6296f21ad1">

**Comment by reyzor1991** [comment]
<img width="866" alt="Screenshot 2024-07-22 at 13 28 35" src="https://github.com/user-attachments/assets/7ce54961-05f0-48ab-b16c-b8045667cea6">

**Comment by Zal4DW** [comment]
as a init version, that per person in the party looks great, heals received would be good?

**Comment by reyzor1991** [comment]
<img width="638" alt="image" src="https://github.com/user-attachments/assets/444ec48c-6016-44fb-890c-90dc5493ec7c">

**Comment by reyzor1991** [comment]
<img width="619" alt="image" src="https://github.com/user-attachments/assets/3dcf7a40-14ba-482a-b7ba-96d5a46004c9">

**Comment by reyzor1991** [comment]
<img width="640" alt="image" src="https://github.com/user-attachments/assets/a48cebed-09d1-4aed-8871-97516d7112d5">

**Comment by reyzor1991** [comment]
<img width="606" alt="image" src="https://github.com/user-attachments/assets/ca4799be-c6d1-4787-b008-342f0cd74a4e">
