### ISSUE TITLE
None of "Pff2e Kingmaker Helper" to work.

### ISSUE THREAD

**Issue by Ulvtand** [reyzor1991/pf2e-wiki#69]
**Describe the bug**
None of "Pff2e Kingmaker Helper" to work.

**To Reproduce**
I have kicked the things that are visible in the picture (player view).

**Expected behavior**
What is visible in the Wiki. Colored hexes with associated images.

**Screenshots**
yup 

![Skärmbild 2024-09-13 133709](https://github.com/user-attachments/assets/0f735ef4-eee0-4dec-9059-62d3fd12ce2f)

**Desktop (please complete the following information):**
 - OS: win11
 - Browser: Chrome
 - Version: all programs / mods are kept up to date

**Smartphone (please complete the following information):**
Why would my mobile info affect this??

**Additional context**
??

**Comment by reyzor1991** [comment]
Any errors in console? Toggle btn is on?

**Comment by reyzor1991** [comment]
<img width="420" alt="image" src="https://github.com/user-attachments/assets/4a7b2bf2-c5b2-4e21-91ad-e2727fd8cc0d">

**Comment by Ulvtand** [comment]
No, it wasn't. Sorry I missed this and I didn't find this in the wiki. Thanks for the help. <3
